# calculate overview

In [1]:
from IPython import display

In [3]:
imgsize = 226 # microns
fielddist = imgsize * 0.90 # overlap
fielddist

In [4]:
resolution = 256

In [5]:
precision = (imgsize) // resolution # integer devision, in microns
display.Math(str(precision) + '\mu m') 

<IPython.core.display.Math object>

In [6]:
xmin = 56.00 # mm
ymin = 30.30
xmax = 78.76
ymax = 43.26

In [7]:
dx = xmax-xmin
dy = ymax-ymin
dx, dy

(22.760000000000005, 12.959999999999997)

In [8]:
xsize = dx + imgsize/1000
ysize = dy + imgsize/1000
xsize, ysize

(24.310000000000006, 14.509999999999998)

In [9]:
xfields = round(xsize*1000 / fielddist)
yfields = round(ysize*1000 / fielddist)
xfields, yfields

(17, 10)

In [10]:
# start
xstart = (xmin - (xsize - dx) / 2) * 1000
ystart = (ymin - (ysize - dy) / 2) * 1000
xstart, ystart

(55225.0, 29525.0)

# calc plane

In [18]:
import numpy as np
from leicacam import CAM

In [19]:
cam = CAM()

In [39]:
def get_position():
    info = cam.get_information()
    return np.array((float(info['xpos'])*1e6, float(info['ypos'])*1e6, float(info['zpos'])*1e6))

In [45]:
p1 = get_position()

In [46]:
p2 = get_position()

In [47]:
p3 = get_position()

In [48]:
p4 = get_position()

In [ ]:
v12 = p2-p1
v13 = p3-p1
v14 = p4-p1
v24 = p4-p2

In [60]:
start = np.array((v12[2], v13[2], v14[2], v24[2]))
start

array([  7.7216,  29.963 ,  57.7524,  50.0308])

- p2 +50um

In [51]:
p1 = get_position()

In [52]:
p2 = get_position()

In [53]:
p3 = get_position()

In [54]:
p4 = get_position()

In [56]:
p1, p2, p3, p4

(array([ 57571.3768,  36788.3747,   8602.8428]),
 array([ 78953.9586,  29936.7523,   8635.6976]),
 array([ 78953.9586,  36714.8787,   8648.6176]),
 array([ 78953.9586,  43360.4319,   8662.119 ]))

In [78]:
mv12 = p2-p1
mv13 = p3-p1
mv14 = p4-p1
mv23 = p3-p2

In [79]:
moved = np.array((mv12[2], mv13[2], mv14[2], mv23[2]))
moved

array([ 32.8548,  45.7748,  59.2762,  12.92  ])

In [80]:
moved - start

array([ 25.1332,  15.8118,   1.5238, -37.1108])

- p1 +46um

In [81]:
p1 = get_position()

In [82]:
p2 = get_position()

In [83]:
p3 = get_position()

In [84]:
p4 = get_position()

In [85]:
p1, p2, p3, p4

(array([ 57571.3768,  36788.3747,   8648.4466]),
 array([ 78953.9586,  29936.7523,   8640.6376]),
 array([ 78953.9586,  36714.8787,   8668.0584]),
 array([ 78953.9586,  43360.4319,   8695.3196]))

In [90]:
m2v12 = p2-p1
m2v13 = p3-p1
m2v14 = p4-p1
m2v24 = p4-p2

In [91]:
moved2 = np.array((m2v12[2], m2v13[2], m2v14[2], m2v24[2]))
moved2

array([ -7.809 ,  19.6118,  46.873 ,  54.682 ])

In [92]:
moved2 - moved

array([-40.6638, -26.163 , -12.4032,  41.762 ])

In [93]:
def move(z_positions, p1, p2, p3):
    # p3 = p4
    z_positions += (p1, p1*0.64, p1*0.64)
    z_positions += (0.5*p2, p2, 0.25*p2)
    z_positions += (0.5*p3, 0.25*p3, p3)

In [96]:
cam.socket.close()